version: '3.6'
services:
  redis:
    image: redis
    hostname: redis
    ports:
      - "6379:6379"


  Sayollo:
    build: .
    image: "sayollo"
    container_name: sayollo
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - WAIT_HOSTS=redis:6379
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    restart: on-failure